import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
COLORS = ("white", "black", "beige", "grey", "blue", "brown")


def main():
    items = []
    for color in COLORS:
        path = ROOT / "assets" / "catalog" / f"manifest_{color}.json"
        items.extend(json.loads(path.read_text(encoding="utf-8")))

    lines = [
        "// Generated by tool/generate_catalog_dart.py. Do not edit by hand.",
        "const generatedCatalogData = <Map<String, String>>[",
    ]
    for item in items:
        fields = {
            "id": item["id"],
            "name": item["style"],
            "category": item["category"],
            "material": item["material"],
            "asset": item["asset"],
            "color": item["colorId"],
        }
        encoded = ", ".join(
            f"'{key}': '{str(value).replace(chr(39), chr(92) + chr(39))}'"
            for key, value in fields.items()
        )
        lines.append(f"  <String, String>{{{encoded}}},")
    lines.append("];")
    output = ROOT / "lib" / "generated_catalog_data.dart"
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"generated {len(items)} entries -> {output}")


if __name__ == "__main__":
    main()
